name: CI Pipeline

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Logging into dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Building the docker image
      run: docker build -t cicd-docker-pipeline .
    - name: Tagging image
      run: docker tag cicd-docker-pipeline:latest krishmarsonia07/cicd-docker-pipeline:latest
    - name: Pushing to dockerhub
      run: docker push krishmarsonia07/cicd-docker-pipeline:latest
